// Editorial recap of the 2026 FIFA World Cup — hand-written from cross-verified
// reporting (ESPN, FIFA, BBC/Sky, Al Jazeera, NPR, NBC, Reuters/AP, Yahoo, TSN,
// Olympics.com). Facts are attributed; unconfirmed totals are deliberately avoided.
//
// Block types rendered by /news/[slug].astro:
//   {t:'p', x}            paragraph (inline HTML allowed)
//   {t:'h', x}            section subheading
//   {t:'q', x, by}        pull quote
//   {t:'stat', v, l}      big stat callout
//   {t:'ul', items:[...]} bullet list (inline HTML allowed)
//   {t:'score', h,a,hs,as,note,stage}   result strip (FIFA codes)

export const ARTICLES = [
  {
    slug: 'baby-goat-vs-the-goat',
    kicker: 'The Final',
    title: 'Baby GOAT vs The GOAT',
    dek: 'On a humid New Jersey night, Lamine Yamal’s Spain outlasted Lionel Messi’s Argentina in extra time — and the torch, at last, changed hands.',
    date: '2026-07-19',
    author: 'WC26 Matchday',
    read: 6,
    tag: 'Final',
    accent: '#e9bb4c',
    emoji: '🐐',
    feature: true,
    lede: 'It was billed as a coronation and it became a passing of the crown. Spain 1, Argentina 0 — settled six minutes into extra time, decided by the coolest head in the coldest moment, and lit throughout by the two names everyone came to see: an 18-year-old and a 39-year-old, the future and the summit of the game.',
    body: [
      { t: 'score', h: 'ESP', a: 'ARG', hs: 1, as: 0, note: 'after extra time — Ferran Torres 106′', stage: 'Final · MetLife Stadium, New York/New Jersey' },
      { t: 'p', x: 'For ninety minutes the Final refused to break. Argentina defended in a low, disciplined block and dared Spain to find a way through; Spain, keeping the ball for long, patient spells, could not. Then the game tilted. Deep in second-half stoppage time <b>Enzo Fernández</b> was shown a second yellow for a foul on the teenage centre-back Pau Cubarsí, and Argentina would play the whole of extra time a man light.' },
      { t: 'p', x: 'The breakthrough came almost immediately after the interval of extra time. <b>Nico Williams</b> drove at a tiring defence and slid the ball across; substitute <b>Ferran Torres</b> arrived to finish it in the <b>106th minute</b>. One goal was all Spain’s defence would ever need.' },
      { t: 'q', x: 'The kid ran the game; the old man chased it. That is how eras end — not with a fall, but with a handover.', by: 'On the Yamal–Messi final' },
      { t: 'h', x: 'The baby GOAT' },
      { t: 'p', x: '<b>Lamine Yamal</b> — 18 when Spain’s campaign began, a Ballon d’Or runner-up already — was the tournament’s gravitational centre even on a night his own goal touch deserted him. Defences bent around him; the space he pulled open made the winner. He does not yet own the game the way the man in the other shirt once did. After this, it is only a matter of time.' },
      { t: 'h', x: 'The GOAT' },
      { t: 'p', x: 'There was no fairytale for <b>Lionel Messi</b>. Playing his record third World Cup final — and, at 39, the oldest outfield player ever to start one — he was shackled, his single clear opening blocked. He finished the tournament with <b>8 goals and 4 assists</b>, the joint-heartbeat of Argentina’s run, but the last act belonged to Spain. He stopped short of announcing an international retirement; whatever comes next, this was almost certainly his final World Cup match.' },
      { t: 'p', x: 'Behind him, <b>Emiliano Martínez</b> was heroic in defeat, credited with an extraordinary <b>11 saves</b> — a shift that kept Argentina alive long past the point their tiring, ten-man legs deserved.' },
      { t: 'p', x: 'Spain lifted their <b>second World Cup</b>, sixteen years after their first, and did it with a defensive record for the ages. The torch, finally, has been passed — and the boy who caught it is only getting started.' },
    ],
    related: ['la-roja-again', 'mbappe-crown', 'the-old-guard-bows'],
  },
  {
    slug: 'la-roja-again',
    kicker: 'Champions',
    title: 'La Roja, again — and this time by suffocation',
    dek: 'Spain won the 2026 World Cup the hard way and the beautiful way at once: total control of the ball, and a back line that conceded exactly one goal in seven matches.',
    date: '2026-07-19',
    author: 'WC26 Matchday',
    read: 5,
    tag: 'Spain',
    accent: '#c60b1e',
    emoji: '🏆',
    lede: 'Great champions are usually remembered for what they scored. Luis de la Fuente’s Spain will be remembered for what they refused to concede. Across the whole tournament — seven matches, the last two in extra time — they let in a single goal.',
    body: [
      { t: 'stat', v: '1', l: 'goal conceded across the entire tournament — a record for a World Cup winner' },
      { t: 'p', x: 'It is the kind of number that reframes a title. Spain did not batter their way to the trophy; they smothered the tournament, monopolising the ball and turning every opponent’s attack into a rumour. In the Final they held roughly two-thirds of possession and manufactured nearly two expected goals to Argentina’s fraction of one.' },
      { t: 'h', x: 'A generation arrives together' },
      { t: 'p', x: 'This was a squad that peaked in unison. <b>Rodri</b>, back to his imperious best after a long knee lay-off, was named the tournament’s best player and took the <b>Golden Ball</b>. Alongside him <b>Pedri</b> conducted, <b>Nico Williams</b> and <b>Lamine Yamal</b> stretched defences, and at the back an 18-year-old, <b>Pau Cubarsí</b>, was so assured he was voted <b>Young Player of the Tournament</b> ahead of his more famous teammate.' },
      { t: 'p', x: 'In goal, <b>Unai Simón</b> collected the <b>Golden Glove</b>, the natural reward for a defence that barely let him be tested.' },
      { t: 'ul', items: [
        '<b>Golden Ball</b> (best player) — Rodri',
        '<b>Golden Glove</b> (best goalkeeper) — Unai Simón',
        '<b>Young Player</b> — Pau Cubarsí',
        '<b>Champions</b> — Spain’s 2nd World Cup, first since 2010',
      ] },
      { t: 'q', x: 'You cannot beat what you cannot reach. For a month, nobody reached Spain.', by: null },
      { t: 'p', x: 'Sixteen years after their first star, La Roja have a second — and, in a core that will still be young at the next World Cup, the frightening suggestion that this was a beginning, not a peak.' },
    ],
    related: ['baby-goat-vs-the-goat', 'mbappe-crown'],
  },
  {
    slug: 'mbappe-crown',
    kicker: 'Golden Boot',
    title: 'Mbappé takes the crown Messi couldn’t keep',
    dek: 'Kylian Mbappé finished as the tournament’s top scorer with 10 goals — and in the process overtook Lionel Messi as the all-time leading World Cup scorer.',
    date: '2026-07-20',
    author: 'WC26 Matchday',
    read: 4,
    tag: 'Golden Boot',
    accent: '#0055a4',
    emoji: '👟',
    lede: 'France went home without the trophy, but their captain left with history. Kylian Mbappé’s 10 goals won the Golden Boot — and pushed him past Messi at the very top of the World Cup’s all-time scoring chart.',
    body: [
      { t: 'stat', v: '10', l: 'Mbappé’s goals — the most at a single World Cup since Gerd Müller in 1970' },
      { t: 'p', x: 'The last two came, fittingly and cruelly, in a losing cause: a brace in France’s wild <b>6-4</b> defeat to England in the third-place playoff. They were his ninth and tenth of the tournament, and they carried a bigger number with them.' },
      { t: 'stat', v: '22', l: 'career World Cup goals for Mbappé — passing Messi (21) as the all-time leader' },
      { t: 'p', x: 'Mbappé became the <b>first player to win the World Cup Golden Boot twice</b>, and did it while overtaking the very man whose farewell tournament this was. <b>Messi</b> finished second in the race on <b>8 goals</b>, adding four assists; <b>Erling Haaland</b>, dragged out in the quarterfinals, ended on <b>7</b>.' },
      { t: 'p', x: 'For France, a semifinal exit and a bronze-medal shootout of a game will sting. For Mbappé, 27 and already alone at the top of the list, the sense is only of a story still being written.' },
    ],
    related: ['baby-goat-vs-the-goat', 'nights-that-shook'],
  },
  {
    slug: 'africa-rising',
    kicker: 'The story of the tournament',
    title: 'Africa’s World Cup: nine of ten, and Morocco again',
    dek: 'A record nine of the ten African teams reached the Round of 32, four of them for the first time — and Morocco carried the flag to the quarterfinals.',
    date: '2026-07-18',
    author: 'WC26 Matchday',
    read: 5,
    tag: 'Africa',
    accent: '#1a7a4c',
    emoji: '🌍',
    lede: 'If the expanded World Cup was designed to widen football’s map, no confederation seized it like Africa. Nine of the continent’s ten entrants advanced from the group stage — a knockout haul that dwarfed anything before it.',
    body: [
      { t: 'stat', v: '9 / 10', l: 'African teams that reached the Round of 32 — the previous record was two' },
      { t: 'p', x: 'The breadth was staggering. <b>South Africa</b>, <b>Ivory Coast</b>, <b>Cape Verde</b> and <b>DR Congo</b> all reached the World Cup knockouts for the <b>first time in their history</b>, joining the more familiar names of Morocco, Senegal, Egypt, Algeria and Ghana.' },
      { t: 'h', x: 'Morocco, once more' },
      { t: 'p', x: 'And at the front, once again, were the <b>Atlas Lions</b>. Four years on from their historic semifinal, Morocco knocked out co-hosts <b>Canada 3-0</b> in the Round of 16 before running into France, who edged a tight quarterfinal <b>2-0</b>. It was the deepest run of any team outside Europe and South America, and it confirmed Morocco’s place among the tournament’s genuine powers rather than its romantics.' },
      { t: 'q', x: 'This was not a fluke or a fairytale. This was a continent arriving in numbers.', by: null },
      { t: 'p', x: 'Cape Verde — a nation of barely half a million — held eventual champions Spain to a goalless draw and reached the last 32 on debut. The expanded format was supposed to democratise the World Cup. In the summer of 2026, Africa cashed the cheque.' },
    ],
    related: ['48-and-counting', 'nights-that-shook'],
  },
  {
    slug: 'hosts-heartbreak',
    kicker: 'The co-hosts',
    title: 'Three hosts, three Round-of-16 exits',
    dek: 'The United States, Mexico and Canada all reached the knockouts on home soil — and all three were gone by the Round of 16.',
    date: '2026-07-07',
    author: 'WC26 Matchday',
    read: 4,
    tag: 'Hosts',
    accent: '#3c78d8',
    emoji: '🇺🇸',
    lede: 'A World Cup on home turf promised the three co-hosts a summer to remember. It delivered a shared, deflating full stop: none of the United States, Mexico or Canada survived the Round of 16.',
    body: [
      { t: 'p', x: '<b>Canada</b> flew highest in the group stage. Jesse Marsch’s side topped their group in style — including a <b>6-0</b> demolition of Qatar lit by a Jonathan David hat-trick — before running into a relentless Morocco and losing <b>3-0</b> in the last 16.' },
      { t: 'score', h: 'USA', a: 'BEL', hs: 1, as: 4, note: 'Round of 16', stage: 'United States eliminated' },
      { t: 'p', x: 'The <b>United States</b>, under Mauricio Pochettino, were the last host standing — and fell hardest, undone <b>4-1</b> by a ruthless Belgium. Malik Tillman’s goal was a footnote on a night that got away early.' },
      { t: 'p', x: '<b>Mexico</b> went out on the grandest stage of all: a <b>3-2</b> defeat to England under the lights and weather delays of the Estadio Azteca, a classic that they ultimately lost to two Jude Bellingham strikes and a Harry Kane penalty.' },
      { t: 'p', x: 'Three nations, three knockout exits, one shared ache. The tournament rolled on without its hosts — but the crowds, and the records they set, did not go anywhere.' },
    ],
    related: ['africa-rising', '48-and-counting'],
  },
  {
    slug: 'nights-that-shook',
    kicker: 'Upsets & classics',
    title: 'The nights that shook the World Cup',
    dek: 'Brazil dumped out by Norway, Germany by Paraguay, and a ten-goal bronze final — the games that defined an unforgettable, unpredictable summer.',
    date: '2026-07-19',
    author: 'WC26 Matchday',
    read: 6,
    tag: 'Upsets',
    accent: '#ff8f5a',
    emoji: '⚡',
    lede: 'Every World Cup has its shocks. This one, stretched to 48 teams and 104 games, had a season’s worth — and some of the finest football of the decade folded in among the ambushes.',
    body: [
      { t: 'h', x: 'Norway 2-1 Brazil' },
      { t: 'p', x: 'The night the tournament turned. <b>Erling Haaland</b> struck twice late to knock out five-time winners <b>Brazil</b> in the Round of 16 — Norway’s first deep run in 28 years, and Brazil’s earliest exit since 1990. Neymar’s stoppage-time penalty came far too late.' },
      { t: 'h', x: 'Paraguay knock out Germany' },
      { t: 'p', x: 'Days after thrashing Curaçao 7-1, <b>Germany</b> were gone — beaten by <b>Paraguay</b> on penalties in the Round of 32, goalkeeper Orlando Gill saving twice. One of the great World Cup upsets, and a grim early flight home for a heavyweight.' },
      { t: 'h', x: 'Cape Verde 0-0 Spain' },
      { t: 'p', x: 'Before they were champions, Spain were held scoreless by <b>Cape Verde</b>, a nation of half a million, despite piling up 27 shots. A single point that a whole country will remember forever.' },
      { t: 'h', x: 'England 6-4 France' },
      { t: 'p', x: 'The bronze final should have been a consolation. Instead it produced the <b>most goals in a World Cup match since 1982</b>. England led <b>4-0</b> at the break — a <b>Bukayo Saka hat-trick</b> among them — before France, roared on by two Mbappé goals, came storming back. England held on, 6-4, for their best World Cup finish since 1966.' },
      { t: 'p', x: 'Add Argentina’s <b>3-2</b> extra-time survival against debutants Cape Verde, and the USA’s collapse against Belgium, and the ledger reads like fiction. It wasn’t. It was just this World Cup.' },
    ],
    related: ['africa-rising', 'mbappe-crown'],
  },
  {
    slug: 'the-old-guard-bows',
    kicker: 'End of an era',
    title: 'The old guard takes its bow',
    dek: 'Cristiano Ronaldo exited in the Round of 16 and Lionel Messi in the Final — two decades of dominance quietly, finally, drawing to a close.',
    date: '2026-07-19',
    author: 'WC26 Matchday',
    read: 4,
    tag: 'Legends',
    accent: '#8f6ad6',
    emoji: '⏳',
    lede: 'For twenty years, one of two names bent every big night around itself. This was the World Cup where both, at last, stepped toward the exit — one early, one at the very end.',
    body: [
      { t: 'p', x: '<b>Cristiano Ronaldo</b>, 41, bowed out in the Round of 16, his Portugal beaten <b>1-0</b> by eventual champions Spain on a late Mikel Merino goal. He left having scored three times to become the <b>first player to score at six different World Cups</b> — a record that may never be touched — and confirmed this was his last, even as he left the door ajar on his international future.' },
      { t: 'p', x: '<b>Lionel Messi</b> went the distance. He dragged Argentina to a third final of his career — his two late assists in the <b>2-1 semifinal</b> comeback over England were vintage — before Spain’s wall and extra time denied him the perfect ending. He finished as the tournament’s second-top scorer and, characteristically, refused to close any doors.' },
      { t: 'stat', v: '34', l: 'World Cup matches for Messi across six tournaments — the most in history' },
      { t: 'p', x: 'They leave the stage as they held it: at opposite ends of the same argument. Behind them, an 18-year-old lifted the trophy. The game, as it always does, moves on.' },
    ],
    related: ['baby-goat-vs-the-goat', 'la-roja-again'],
  },
  {
    slug: '48-and-counting',
    kicker: 'The verdict',
    title: '48 teams, 104 matches, one very big experiment',
    dek: 'The first 48-team World Cup was bigger than any before it — and, from record crowds to first-time nations, it mostly made the case for itself.',
    date: '2026-07-20',
    author: 'WC26 Matchday',
    read: 5,
    tag: 'The format',
    accent: '#58ddff',
    emoji: '🌐',
    lede: 'The math alone was daunting: 48 teams, 104 matches, three host nations, a new Round of 32 bolted on before the knockouts most fans knew. The fear was dilution. What arrived, more often than not, was expansion done right.',
    body: [
      { t: 'p', x: 'The crowds answered first. Spread across the United States, Canada and Mexico, the tournament <b>broke the all-time World Cup attendance record</b> set in 1994, playing to packed stadiums almost everywhere. Whatever the format debate, the appetite was never in question.' },
      { t: 'h', x: 'New flags, new stories' },
      { t: 'p', x: 'The expansion’s best argument was the map. <b>Curaçao</b> — a Caribbean island of around 156,000 people — became the <b>smallest nation ever to play a men’s World Cup</b>, and took a point off Ecuador to prove it belonged. <b>Cape Verde</b>, <b>Jordan</b> and <b>Uzbekistan</b> all made their debuts; Cape Verde reached the knockouts.' },
      { t: 'ul', items: [
        'First World Cup with <b>48 teams</b> and <b>104 matches</b>',
        'First hosted by <b>three nations</b> at once',
        'A new <b>all-time attendance record</b>, breaking 1994’s mark',
        'The <b>most goals</b> in World Cup history',
        'Four debutants; the smallest nation ever to appear',
      ] },
      { t: 'h', x: 'The other side' },
      { t: 'p', x: 'It was not flawless. Some group-stage mismatches were brutal — Germany’s <b>7-1</b> over Curaçao among them — and a 104-match calendar asked a great deal of players and travelling fans across a continent-sized tournament. But the knockouts were relentless, the upsets frequent, and the final worthy. The 48-team World Cup will be back in 2030. On the evidence of 2026, it has earned the encore.' },
    ],
    related: ['africa-rising', 'hosts-heartbreak'],
  },
];

export const bySlug = Object.fromEntries(ARTICLES.map(a => [a.slug, a]));
